/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBookmarkAddRouteImport } from './routes/_authenticated/bookmark-add'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedFeedsIndexRouteImport } from './routes/_authenticated/feeds/index'
import { Route as AuthenticatedBookmarksIndexRouteImport } from './routes/_authenticated/bookmarks/index'
import { Route as AuthenticatedArticlesIndexRouteImport } from './routes/_authenticated/articles/index'
import { Route as AuthenticatedNotificationsIdRouteImport } from './routes/_authenticated/notifications/$id'
import { Route as AuthenticatedBookmarksIdRouteImport } from './routes/_authenticated/bookmarks/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookmarkAddRoute =
  AuthenticatedBookmarkAddRouteImport.update({
    id: '/bookmark-add',
    path: '/bookmark-add',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedsIndexRoute = AuthenticatedFeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookmarksIndexRoute =
  AuthenticatedBookmarksIndexRouteImport.update({
    id: '/bookmarks/',
    path: '/bookmarks/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArticlesIndexRoute =
  AuthenticatedArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIdRoute =
  AuthenticatedNotificationsIdRouteImport.update({
    id: '/notifications/$id',
    path: '/notifications/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookmarksIdRoute =
  AuthenticatedBookmarksIdRouteImport.update({
    id: '/bookmarks/$id',
    path: '/bookmarks/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bookmark-add': typeof AuthenticatedBookmarkAddRoute
  '/bookmarks/$id': typeof AuthenticatedBookmarksIdRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/articles/': typeof AuthenticatedArticlesIndexRoute
  '/bookmarks/': typeof AuthenticatedBookmarksIndexRoute
  '/feeds/': typeof AuthenticatedFeedsIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bookmark-add': typeof AuthenticatedBookmarkAddRoute
  '/bookmarks/$id': typeof AuthenticatedBookmarksIdRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/articles': typeof AuthenticatedArticlesIndexRoute
  '/bookmarks': typeof AuthenticatedBookmarksIndexRoute
  '/feeds': typeof AuthenticatedFeedsIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/bookmark-add': typeof AuthenticatedBookmarkAddRoute
  '/_authenticated/bookmarks/$id': typeof AuthenticatedBookmarksIdRoute
  '/_authenticated/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/_authenticated/articles/': typeof AuthenticatedArticlesIndexRoute
  '/_authenticated/bookmarks/': typeof AuthenticatedBookmarksIndexRoute
  '/_authenticated/feeds/': typeof AuthenticatedFeedsIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bookmark-add'
    | '/bookmarks/$id'
    | '/notifications/$id'
    | '/articles/'
    | '/bookmarks/'
    | '/feeds/'
    | '/notifications/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bookmark-add'
    | '/bookmarks/$id'
    | '/notifications/$id'
    | '/articles'
    | '/bookmarks'
    | '/feeds'
    | '/notifications'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/bookmark-add'
    | '/_authenticated/bookmarks/$id'
    | '/_authenticated/notifications/$id'
    | '/_authenticated/articles/'
    | '/_authenticated/bookmarks/'
    | '/_authenticated/feeds/'
    | '/_authenticated/notifications/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookmark-add': {
      id: '/_authenticated/bookmark-add'
      path: '/bookmark-add'
      fullPath: '/bookmark-add'
      preLoaderRoute: typeof AuthenticatedBookmarkAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feeds/': {
      id: '/_authenticated/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof AuthenticatedFeedsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks/': {
      id: '/_authenticated/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof AuthenticatedBookmarksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/articles/': {
      id: '/_authenticated/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof AuthenticatedArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/$id': {
      id: '/_authenticated/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof AuthenticatedNotificationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks/$id': {
      id: '/_authenticated/bookmarks/$id'
      path: '/bookmarks/$id'
      fullPath: '/bookmarks/$id'
      preLoaderRoute: typeof AuthenticatedBookmarksIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBookmarkAddRoute: typeof AuthenticatedBookmarkAddRoute
  AuthenticatedBookmarksIdRoute: typeof AuthenticatedBookmarksIdRoute
  AuthenticatedNotificationsIdRoute: typeof AuthenticatedNotificationsIdRoute
  AuthenticatedArticlesIndexRoute: typeof AuthenticatedArticlesIndexRoute
  AuthenticatedBookmarksIndexRoute: typeof AuthenticatedBookmarksIndexRoute
  AuthenticatedFeedsIndexRoute: typeof AuthenticatedFeedsIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookmarkAddRoute: AuthenticatedBookmarkAddRoute,
  AuthenticatedBookmarksIdRoute: AuthenticatedBookmarksIdRoute,
  AuthenticatedNotificationsIdRoute: AuthenticatedNotificationsIdRoute,
  AuthenticatedArticlesIndexRoute: AuthenticatedArticlesIndexRoute,
  AuthenticatedBookmarksIndexRoute: AuthenticatedBookmarksIndexRoute,
  AuthenticatedFeedsIndexRoute: AuthenticatedFeedsIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
